import {configureFonts} from 'react-native-paper';

export const fonts = configureFonts({
  config: {
    default: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    displayLarge: {
      fontFamily: 'RubikBubbles-Regular',
      fontWeight: 'bold',
      letterSpacing: 1,
      lineHeight: 30,
      fontSize: 20,
    },
    displayMedium: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    displaySmall: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    headlineLarge: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    headlineMedium: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    headlineSmall: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    titleLarge: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    titleMedium: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    titleSmall: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    labelLarge: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    labelMedium: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    labelSmall: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    bodyLarge: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    bodyMedium: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
    bodySmall: {
      fontFamily: 'Sevillana-Regular',
      fontWeight: 'normal',
      letterSpacing: 0,
      lineHeight: 20,
      fontSize: 12,
    },
  },
});
